### ISSUE TITLE
Error when attempting to connect DataSource to react native View

### ISSUE THREAD

**Issue by almilli** [react-dnd/react-dnd#851] opened 2017-08-17 15:34 UTC
I am starting to work on a react-native backend to react-dnd and I'm porting the Chess example and noticed that once I use a <View> instead of <div> then I run into this error:

"Only native element nodes can now be passed to React DnD connectors. You can either wrap View into a &lt;div&gt;, or turn it into a drag source or a drop target itself."

I tracked it down to wrapConnectorHooks.js.  I see the comment about the react-dom.  It seems like this check shouldn't be here at all and if it should be anywhere, it should be handled in the backend where the backend knows that there is a dom at all.  It's kind of tying react-dnd to web browsers only.

Here is the problem code. In the case of a React Native View component, the element.type is a function and not a string like it is assuming
```
function throwIfCompositeComponentElement(element) {
  // Custom components can no longer be wrapped directly in React DnD 2.0
  // so that we don't need to depend on findDOMNode() from react-dom.
  if (typeof element.type === 'string') {
    return;
  }

  var displayName = element.type.displayName || element.type.name || 'the component';

  throw new Error('Only native element nodes can now be passed to React DnD connectors.' + ('You can either wrap ' + displayName + ' into a <div>, or turn it into a ') + 'drag source or a drop target itself.');
}
```

and here is the render method in Knight.js that was ported.
```
render() {
    const { connectDragSource, isDragging } = this.props;
    return connectDragSource(
      <View><Text
        style={{
          fontSize: 40,
          fontWeight: 'bold',
          cursor: 'move',
          opacity: isDragging ? 0.5 : 1,
        }}>♘</Text>
      </View>
    );
  }
```

**Comment by yanickrochon** [comment] 2017-09-18 20:40
Wrapping the component into a native element solves it but breaks my UI.

Why aren't composite component accepted??

**Comment by jeroenransijn** [comment] 2017-11-15 03:09
Possible duplicate of #903.

**Closed** 2019-07-13 08:48 UTC
Labels: wontfix
