### ISSUE TITLE
Can't drag down on iOS 13

### ISSUE THREAD

**Issue by fokayx** [react-dnd/react-dnd#1585] opened 2019-10-25 09:58 UTC
**Describe the bug**
While iOS upgrade to 13, our dnd sortable list component can drag up but can't drag down. All it worked in iOS < 12. Is it a bug in iOS 13 ? Have any idea?

**Desktop (please complete the following information):**

- OS: iOS
- Browser: chrome, safari
- Version 78.0.3904.67

**Comment by fsp** [comment] 2019-10-25 12:53
I've also observed this problem starting iOS 13.1 and it is still present in iOS 13.2 beta. I am using a custom drag layer with the touch backend. 

This seems to be an issue with WebKit on iOS specifically.

**Comment by zhusee2** [comment] 2019-10-30 10:19
Also experiencing the same thing on iOS 13.2 release. It seems to be happening in the “sorting” context.

While you can drag a node anywhere trouble-free, if you re-render a list when you drag item A downward onto item B, you can suddenly loose control to the dragging node. But the drag isn't considered as **end**–the `endDrag()` callback is triggered only when your finger really leaves the screen.

It almost happen every time as you drag downward and and re-render. It can also happen when you drag upward, but that's a relatively rare case.

**Comment by zhusee2** [comment] 2019-10-31 07:09
I took a closer look at the touch backend, and I found it's stuck at [TouchBackend.ts#L390][1] because it can't find event client offset.

Turned out that in iOS 13, `event.targetTouches` list from `touchmove` event can be cleared out in the above situation, even when the only `Touch` target in its `event.touches` is the same node from `touchstart` event.

[1]: https://github.com/react-dnd/react-dnd/blob/v9.4.0/packages/core/touch-backend/src/TouchBackend.ts#L390

**Comment by fsp** [comment] 2019-10-31 10:45
This may be related to [this webkit issue](https://bugs.webkit.org/show_bug.cgi?id=203232)

**Comment by varseb** [comment] 2019-11-12 00:50
Same issue here

**Comment by thenano** [comment] 2019-12-02 09:01
I'm also experiencing this and have confirmed that everything works as expected on iOS 12.
Thanks for providing a fix @zhusee2 !
Hopefully the fix can be merged soon. Thanks all

**Closed** 2019-12-02 22:49 UTC
