### ISSUE TITLE
New DndProvider multiple HTML5 backends issue

### ISSUE THREAD

**Issue by Nico142** [react-dnd/react-dnd#1417] opened 2019-06-20 14:25 UTC
**Describe the bug**
Since using the new `DndProvider` I get an **Cannot have two HTML5 backends at the same time.** error after re-rendering the component where `DndProvider` is set.
According to the documentation the `DndProvider` should be at the very top of the application but only one re-render will break the whole app. Also when using the react-router it's not the best idea to always place it at the top.

**To Reproduce**
1. Place the `DndProvider` in a component
2. Cause a re-render e.g. with useState
3. Application will break

**Expected behavior**
The `DndProvider` should use the already created backend.

**Example**
https://codesandbox.io/s/gs988

**Additional context**
The legacy HOC `DragDropContext` didn't have this issue.

**Comment by rtxu** [comment] 2019-06-21 10:11
When I go through the official tutorial, it happens to me.

**Comment by rtxu** [comment] 2019-06-21 10:17
use DragDropContext insteam of DndProvider, and keep other code intact.
The problem is resolved.

**Comment by darthtrevino** [comment] 2019-06-21 18:28
If you put the DndProvider at the top part of your tree where it won't be rerendered, that will work as a workaround. I'll look into making it more resistant to rerenders

**Comment by darthtrevino** [comment] 2019-06-21 19:06
Fixed in https://github.com/react-dnd/react-dnd/pull/1422, which will be released in the next patch version

**Closed by darthtrevino** 2019-06-21 19:06 UTC
Labels: bug

**Comment by suposplus** [comment] 2020-08-19 05:41
> **Describe the bug**
> Since using the new `DndProvider` I get an **Cannot have two HTML5 backends at the same time.** error after re-rendering the component where `DndProvider` is set.
> According to the documentation the `DndProvider` should be at the very top of the application but only one re-render will break the whole app. Also when using the react-router it's not the best idea to always place it at the top.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Place the `DndProvider` in a component
> 2. Cause a re-render e.g. with useState
> 3. Application will break
> 
> **Expected behavior**
> The `DndProvider` should use the already created backend.
> 
> **Example**
> https://codesandbox.io/s/gs988
> 
> **Additional context**
> The legacy HOC `DragDropContext` didn't have this issue.
@Nico142 
Yeap, I agree with you, but I viewed the page that you provided, it happen again.
Here's what I did with the different versions.
>=8.0 :https://codesandbox.io/s/react-dnd-backend-issue-forked-uyf8z?file=/src/index.js
<8.0 :https://codesandbox.io/s/react-dnd-backend-issue-forked-bccjz?file=/src/index.js
