### ISSUE TITLE
Drag preview jumps on drag

### ISSUE THREAD

**Issue by cherston** [react-dnd/react-dnd#437] opened 2016-04-12 15:44 UTC
When using this library, my drag preview image jumps with respect to the drag source unless I click the upper left corner of the image. The amount that the drag preview jumps is dependent on how offset my mouse is from the upper left corner when beginning the drag. 

Desired behavior is for the image not to jump. I see that there are parameters available for detecting the mouse offset, (and indeed I can accurately read in the initialClientOffset) but I cannot set the offset appropriately, and I believe the library is supposed to do the right thing by default and avoid jumping.

**Comment by froatsnook** [comment] 2016-04-12 16:00
What is your browser's zoom level?  And which browser are you using?  This might be a duplicate of #430.

**Comment by cherston** [comment] 2016-04-12 16:05
I am using Chrome 49.0.2623.110. You are correct in thinking to check browser zoom: set at 50%. When I increase to 100%, issue disappears. Therefore, yes this is a dupe of #430. However, would be very useful if drag preview worked independent of browser zoom, or if a temporary workaround could be proposed. Thank you!

**Comment by froatsnook** [comment] 2016-04-12 22:02
Yes it would be nice if it worked!  I tested an html5 drag and drop example [here] (http://www.w3schools.com/html/html5_draganddrop.asp) and it worked fine with zoom.  Therefore I think it should be possible. I don't know of any workarounds, unfortunately, but I will leave this issue open for now, and hopefully someone (maybe me, maybe you?) will fix it.

**Comment by delaaxe** [comment] 2019-06-03 07:24
Also having this issue. I have a custom drag layer that flashes at an incorrect location on drag start.

Issue comes from sourceClientOffset giving wrong values. What's perplexing is that after dragstart, values on first 2 renders are ok, *values on the following 2 renders are wrong* (off by about -100px in each direction) then fine again on subsequent renders of the drag.

I have no idea why

**Comment by stevenkkim** [comment] 2019-06-25 16:51
I'm using Chrome 75 on Windows 10 and I am also experiencing the jumping issue in the example: [http://react-dnd.github.io/react-dnd/examples/sortable/simple](http://react-dnd.github.io/react-dnd/examples/sortable/simple)

**Closed** 2019-08-31 17:21 UTC
Labels: triage, wontfix

**Comment by openSourceBugs** [comment] 2021-11-10 01:02
The docs basically say "zero flicker" and there is flicker happening.  Why the cognitive dissonance? Issue can be seen at   https://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer  on the JavaScript tab.
