### ISSUE TITLE
Crashing in isOver with empty targetId

### ISSUE THREAD

**Issue by Kadrian** [react-dnd/react-dnd#1245] opened 2019-03-07 00:07 UTC
**Describe the bug**
I have a connected drop target that is removed from the DOM, once something is dropped on to it.

Now since upgrading to `v7.1.0`, I'm getting
```
Uncaught TypeError: Cannot read property '0' of undefined
```
in the `monitor.isOver()` call inside the `collect` function. 
Somehow, it sees that the collect function is still called one more time, after the drop target has been removed (`targetId` is undefined).

**Interesting**
- Downgrading back to `6.0.0` resolved the issue.
- Also, using a short `setTimeout` wrapper around my callback that removed the drop target, resolved the issue.

Any idea what could cause that?

**To Reproduce**
1. Connect a Drop target, call `monitor.isOver()` in `collect`
2. in the target, dispatch an action inside `drop(...)` that removes the drop target
3. See error

**Expected behavior**
There is no timing issue with `isOver` and drop targets can be immediately removed.

**Screenshots**
<img width="458" alt="bildschirmfoto 2019-03-07 um 00 58 04" src="https://user-images.githubusercontent.com/1403093/53922542-19d12900-4075-11e9-963b-0e9a1279dcb2.png">

**Desktop (please complete the following information):**
 - OS: os x
 - Browser chrome
 - react-dnd / html5 backend `7.1.0`

**Comment by RaoHai** [comment] 2019-03-07 02:54
Same issue

**Comment by RaoHai** [comment] 2019-03-07 03:58
I tried to revert this change https://github.com/react-dnd/react-dnd/commit/0feb250b7ee90483e31f3bc159ebf946980d53a7#diff-ac418ba19283aec1fb0b70e6570c5613 and resolved.. .

**Comment by safonoi** [comment] 2019-03-07 09:22
Same issue.
Waiting for fix.
Now downgraded back to v7.0.2

**Comment by cfrank** [comment] 2019-03-07 13:21
Confirmed we are receiving the same issue - Reverting to 7.0.2 fixes the issue

**Comment by cfrank** [comment] 2019-03-07 13:32
This is being caused because the change at 0feb250b7ee90483e31f3bc159ebf946980d53a7 is allowing target ID to be `undefined` but nobody checked the PR with that change for `isOverTarget`

Currently it's prototype is:

`public isOverTarget(targetId: string, options = { shallow: false })`

unlike the other functions which changed in that pr which move `targetId` / `sourceId` to

`targetId: string | undefined`
`sourceId: string | undefined`

and check:

```
if (!targetId) {
    return false;
}
```

A fix for this issue will be to check for `targetId` being `undefined` here: https://github.com/mattkrick/react-dnd/blob/aafcf7d67f8b3a2035b561e97b7874e1064447e4/packages/dnd-core/src/DragDropMonitorImpl.ts#L128

**Comment by darthtrevino** [comment] 2019-03-07 20:06
This should be fixed by cfrank's PR in a release today

**Closed by darthtrevino** 2019-03-07 20:06 UTC

**Comment by Kadrian** [comment] 2019-03-08 13:58
Amazing, guys, thanks @cfrank
