### ISSUE TITLE
dragging over an element causes hover state

### ISSUE THREAD

**Issue by ndao** [react-dnd/react-dnd#476] opened 2016-06-23 20:42 UTC
I have a hover state (header becomes blue). When I drag item A to item B and the dragged preview hovers over item C, item C hover state is stuck until i hover over to reset it.

![drag-hover](https://cloud.githubusercontent.com/assets/8940740/16319275/6bbabd54-3947-11e6-9048-518faaa73589.gif)

Chrome 51.0.2704.84
Safari 9.1.1 (11601.6.17)
Firefox 47.0

**Comment by denyslukovsc** [comment] 2016-12-02 16:57
Same here

**Comment by ndao** [comment] 2016-12-02 21:36
@denyslukovsc , nope :)

**Comment by NeXTs** [comment] 2016-12-02 21:59
@paulirish Hey Paul, maybe you do have idea, is it known Chrome bug? Or this behaviour is intentional?
Problem is - after dropping dragged element, it's hover state remains active

**Comment by kelvinkoko** [comment] 2016-12-12 10:42
Same here

**Comment by paulirish** [comment] 2016-12-12 22:12
@NeXTs we would have to see if we can reproduce this in a ~50line minimal repro to really know.

I haven't heard of a bug like this bug I don't follow the dnd stuff too closely.

**Comment by NeXTs** [comment] 2016-12-12 22:39
@ndao @kelvinkoko do you have something to show?
I'll try to reproduce it in small snippet tomorrow

**Comment by NeXTs** [comment] 2016-12-13 13:17
@paulirish ok I was able to reproduce this with other library called [Sortable](https://github.com/RubaXa/Sortable)

https://codepen.io/NeXTs/pen/yVRexp
See, after sorting - dragging element keeps hover state (so that pseudo-element with box shadow still visible)

![8f92021593a7cd96ae6fb95b94e99e21](https://cloud.githubusercontent.com/assets/1753208/21141587/aee7e5ac-c146-11e6-85f5-20743a9820c8.gif)
![feafeb9a491cb13026037cc4761f74f1](https://cloud.githubusercontent.com/assets/1753208/21141673/2546266e-c147-11e6-90c3-04fb1dacffdb.gif)

**Comment by kelvinkoko** [comment] 2016-12-15 10:08
Maybe it is related to this webkit bug?
https://bugs.webkit.org/show_bug.cgi?id=134555

any workaround suggestion?

**Comment by NeXTs** [comment] 2016-12-15 10:38
@kelvinkoko yep, it looks really similar. thanks for research

**Comment by andreafeccomandi** [comment] 2017-05-18 21:06
Same problem here.

Any workaround?

**Comment by ManishaKundoor-Reflektion** [comment] 2017-06-21 19:55
This work around, https://bugs.chromium.org/p/chromium/issues/detail?id=410328#c5
did the trick for us.

**Comment by nicksergeant** [comment] 2017-08-11 16:08
@ManishaKundoor-Reflektion would you be willing to share your workaround here? We're running into the same issue but temporarily setting `pointer-events` to `none` is not working:

```
    jQuery('ul.widgets.sortable').css('pointer-events', 'none');
    setTimeout(function() {
      jQuery('ul.widgets.sortable').css('pointer-events', 'all');
    }, 0);
```

**Comment by liorbrauer** [comment] 2017-08-20 08:51
As @ManishaKundoor-Reflektion pointed to in the link, this is a long standing bug in chromium (and a very annoying one that adversely affects drag and drop functionality in the browser). 

The work-around mentioned in that comment isn't really viable in many cases (including mine), and isn't scalable. 

Really hoping this gets fixed in the near future :/

**Comment by justinpincar** [comment] 2017-09-19 19:54
Same here - would love to know a workaround since the one posted above just messes things up more in my case.

**Comment by ashwanipayal** [comment] 2018-05-29 11:12
i am facing as well

**Comment by msadahiro** [comment] 2018-07-19 00:32
Wanted to see if there was a work around of this?

**Closed** 2019-07-13 02:48 UTC
Labels: wontfix

**Comment by danny-andrews** [comment] 2020-11-12 01:00
Same issue. Sad days. :(

**Comment by amirabengaied** [comment] 2020-11-13 08:51
Same issue.

**Comment by danny-andrews** [comment] 2020-11-13 23:58
For anyone looking for a workaround, this is what I've hacked together:

component.jsx:

```js
const [disableHoverStyles, setDisableHoverStyles] = setState(false);
const [{}, drag] = useDrag({
  // ...
  begin: () => {
    setDisableHoverStyles(true);
  },
  end: () => {
    setDisableHoverStyles(false);
  },
  // ...
  },
});

const classes = classnames({
  'disable-hover-styles': disableHoverStyles,
})

return (
  <ol className={classes}
    // ...
  </ol>
);
```

component.css
```css
.disable-hover-styles button:hover {
  background: inherit !important;
}
```

Basically, when drag starts, I add a class which disables hover styles on elements inside the drag container. When drag ends, I remove that class. It's a little heavy-handed, and requires using `!important` (gross!) but it works for my purposes.

**Comment by ipoly** [comment] 2022-02-07 03:37
I use this workaround:

```
.child:hover {
    /* hover style */
} 

.parent:active .child:hover {
    /* clear hover style */
} 
```

**Comment by danielbellmas** [comment] 2022-07-19 08:58
**This worked for me:**
Instead of using `monitor.isDragging()` to set the isDragging state use -> `!!monitor.getItem()`, like so:
```js
const [{ opacity, isDragging }, drag] = useDrag({
    type: itemType,
    item: () => originalItem,
    canDrag,
    collect: (monitor: DragSourceMonitor) => ({
      opacity: monitor.isDragging() ? 0 : 1,
      isDragging: !!monitor.getItem()
    })
  });
```
That way the isDragging state will be `false` whenever no dragging is occurring and `true` when an item is dragged.

and the hover styles will be applied only when `isDragging` is `false`:

```js
 <Box
      ref={ref}
      sx={{
        opacity,
        ...(!isDragging && {
            '&:hover': {
              borderRadius: '4px',
              border: `1px solid blue`
            }
          })
      }}
      data-handler-id={handlerId}
    >
....
</Box>
```
