### ISSUE TITLE
Hooks API Discussion

### ISSUE THREAD

**Issue by jacobp100** [react-dnd/react-dnd#1148] opened 2018-10-26 21:39 UTC
Somebody was going to ask eventually! The new hooks API could possibly help here. I think most of the API can pretty much stay the same, with the HOC mapping directly into a hook.

I do wonder if we can replace `connectDragSource` and `connectDropTarget` with just passing in the value of `useRef`. It could definitely make stuff cleaner if that's possible!

**Comment by darthtrevino** [comment] 2018-10-29 06:42
I can't wait to start using hooks in this library. As soon as the types are baked for the alpha we can set up a migration branch

**Comment by darthtrevino** [comment] 2018-11-06 19:06
I'm playing around in a branch: experiment/hooks, just to think about how this API might look. The BoardSquare component is looking like this:

```jsx

const dropTarget = createDropTarget(ItemTypes.KNIGHT, {
	canDrop: (props: BoardSquareProps) => canMoveKnight(props.x, props.y),
	drop: (props: BoardSquareProps) => moveKnight(props.x, props.y),
})

const BoardSquare = ({ x, y, children }) => {
	const black = (x + y) % 2 === 1
	const [connectDropTarget, isOver, canDrop] = useDnd(
		dropTarget,
		connect => connect.dropTarget,
		(connect, monitor) => !!monitor.isOver,
		(connect, monitor) => !!monitor.canDrop,
	)

	return connectDropTarget(
		<div>
			<Square black={black}>{children}</Square>
			{isOver && !canDrop && <Overlay color={'red'} />}
			{!isOver && canDrop && <Overlay color={'yellow'} />}
			{isOver && canDrop && <Overlay color={'green'} />}
		</div>,
	)
}
```

**Comment by darthtrevino** [comment] 2018-11-06 19:07
So the idea here is that the createDragSource and createDropTarget would specify the item type and predicates about its behavior, and then the hook would wire this into the DnD backend and provide collected props.

**Comment by jacobp100** [comment] 2018-11-07 10:06
What branch are you working on? I'm wondering if we can remove `connectDropTarget` all together using refs. I'd love to see if I can get it working on your branch!

```js
const dropTarget = createDropTarget(ItemTypes.KNIGHT, {
	canDrop: (props: BoardSquareProps) => canMoveKnight(props.x, props.y),
	drop: (props: BoardSquareProps) => moveKnight(props.x, props.y),
})

const BoardSquare = ({ x, y, children }) => {
	const dropTargetElement = useRef(null);
	const black = (x + y) % 2 === 1
	const [isOver, canDrop] = useDnd(
		dropTargetElement,
		dropTarget,
		...
	)

	return (
		<div ref={dropTargetElement}>
			<Square black={black}>{children}</Square>
			{isOver && !canDrop && <Overlay color={'red'} />}
			{!isOver && canDrop && <Overlay color={'yellow'} />}
			{isOver && canDrop && <Overlay color={'green'} />}
		</div>
	)
}
```

**Comment by yched** [comment] 2018-11-07 10:15
@jacobp100 I think I've seem similar hook-based APIs where the ref is provided and returned by the hook itself (like `const [isOver, canDrop, ref] = useDnd(...)`), ready for the consuming component to place in its JSX tree)

**Comment by jacobp100** [comment] 2018-11-07 10:32
I suppose that works. It makes it harder to use the ref in multiple hooks, but there's nothing to stop you writing something that combines multiple refs into a single ref. What library was this?

Guess we gotta see what the convention on this is!

**Comment by yched** [comment] 2018-11-07 10:57
> It makes it harder to use the ref in multiple hooks, but there's nothing to stop you writing something that combines multiple refs into a single ref

True, and true :-)

> What library was this?

Can't seem find it again atm :-/ - lots of experiments around hooks in the past fortnight...

There's https://github.com/beizhedenglong/react-hooks-lib that does 
`const { hovered, bind } = useHover(); return <div {...bind}>{hovered ? 'yes' : 'no'}</div>;` 
(which I guess means `bind` includes a ref ?)

But I do remember seeing some other API returning a ref straight from the hook.

**Comment by darthtrevino** [comment] 2018-11-07 19:15
There's not much there, and it's not building at the moment, but the branch I'm in is `experiment/hooks`

**Comment by darthtrevino** [comment] 2018-11-07 19:20
Just iterating here: 

```jsx
const dropTarget = createDropTarget(ItemTypes.KNIGHT, {
	canDrop: (props: BoardSquareProps) => canMoveKnight(props.x, props.y),
	drop: (props: BoardSquareProps) => moveKnight(props.x, props.y),
})

const BoardSquare = ({ x, y, children }) => {
	const black = (x + y) % 2 === 1
        const ref = useRef(null)
	const [connectDropTarget, isOver, canDrop] = useDnd(
		connect => connect(dropTarget, ref),
		(connect, monitor) => !!monitor.isOver,
		(connect, monitor) => !!monitor.canDrop,
	)

	return (
		<div ref={ref}>
			<Square black={black}>{children}</Square>
			{isOver && !canDrop && <Overlay color={'red'} />}
			{!isOver && canDrop && <Overlay color={'yellow'} />}
			{isOver && canDrop && <Overlay color={'green'} />}
		</div>,
	)
}
```

**Comment by darthtrevino** [comment] 2018-11-07 19:30
This is how chaining dragSource & dropTarget might work, if we use the ref as the first argument, the rest arguments can connect it to multiple dnd concepts.


```
const dropTarget = createDropTarget(ItemTypes.CARD, {
	canDrop: () => false
	hover(props, monitor) {
		/**/
	},
})
const dragSource = createDragSource(ItemTypes.CARD, {
	beginDrag: props => /*...*/,
	endDrag: (props, monitor) => /*...*/
})

function Card({ text }) {
	const ref = useRef(null)
	const [isDragging] = useDnd(
		connect => connect(ref, dropTarget, dragSource),
		monitor => monitor.isDragging,
		)
	const opacity = isDragging ? 0 : 1

	return (
		<div style={{ ...style, opacity }}>
			{text}
		</div>
	)
}
```

**Comment by darthtrevino** [comment] 2018-11-07 19:41
So useDnd would look like

```jsx

export type DndConcept = DragSource | DropTarget
export type ConnectorFunction = (connector: Connector /*new type*/) => void
export type CollectorFunction<T> = (monitor: DragDropMonitor) => T

export function useDnd(
	connector: ConnectorFunction,
	...collectors: CollectorFunction[]
): any[] {
	const dragDropManager = useDragDropManager()
        // magic
       return collectedProperties
}

export function useDragDropManager(): DragDropManager {
	return useContext(DragDropContextType)
}

```

**Comment by jacobp100** [comment] 2018-11-07 20:44
Crazy idea, what if we didn't bother with `connect` and `monitor`?

```js
const Test = props => {
  const ref = useRef(null);
  const { isDragging } = useDragSource(ref, ItemTypes.CARD, {
    canDrag: props.enabled,
    beginDrag: () => ({ id: props.id }),
  });

  return <div ref={ref} style={{ color: isDragging ? 'red' : 'black' }} />
}
```

**Comment by darthtrevino** [comment] 2018-11-07 21:02
I think you can get rid of connect, but I'm not sure about monitor, it's where you get your props like isDragging from

**Comment by darthtrevino** [comment] 2018-11-07 21:03
so maybe `useDragSource(ref, <type>, <spec>, <collect>)`. That's a lot of arguments, and it may be weird to have two fat objects next to each other

**Comment by jacobp100** [comment] 2018-11-07 21:04
Can we just return all the props from monitor though?

**Comment by darthtrevino** [comment] 2018-11-07 21:52
Maybe, I think this is the only method that would cause trouble: https://github.com/react-dnd/react-dnd/blob/84db06edcb94ab3dbb37e8fe89fcad55b1ad07ce/packages/react-dnd/src/interfaces.ts#L117

IIRC, the DragSourceMonitor, DropTragetMonitor, and DragLayerMonitor all thunk down to the DragDropMonitor class. So I don't think we'd run into naming collisions, but I'd double check that.

**Comment by jacobp100** [comment] 2018-11-12 22:04
@yched Just playing around with this and hooks, we do have to pass the ref in. See the case when something is both a source and a target,

```js
const Test = () => {
  const ref = useRef(null)
  const source = useDragSource(ref, …props)
  const target = useDragTarget(ref, …props)

  return source.connect(target.connect((
    <div>…</div>
  ))
}
```

**Comment by yched** [comment] 2018-11-12 22:50
@jacobp100 indeed, makes sense.

**Comment by jacobp100** [comment] 2018-11-13 10:52
Okay, idea,

```js
const Test = (props) => {
  const ref = useRef(null)
  const [sourceConnector, sourceMonitor] = useDragSource(ref, {
    beginDrag: () => ({ id: props.id })
  })
  const [targetConnector, targetMonitor] = useDragTarget(ref, {
    drop: () => alert(targetMonitor.getItem().id)
  })
  const { isDragging } = useMonitorSubscription(targetMonitor, monitor => ({
    isDragging: monitor.isDragging()
  })

  return sourceConnector.dragSource(targetConnector.dropTarget((
    <div>…</div>
  ))
}
```

And `useMonitorSubscription` can do a shallow equal on the object to reduce updates

**Comment by jacobp100** [comment] 2018-11-17 12:49
I've taken an initial look over [here](https://github.com/jacobp100/react-dnd/tree/master/packages/react-dnd/src/hooks). Not tested, but should show what I want to do!

**Comment by k15a** [comment] 2018-11-28 13:53
I having `useDragSource(ref, <type>, <spec>, <collect>)` is the proposal which works really nice and doesn't bring to much api changes. The only difference is that you change from a hoc to a hook.

Also having to fat object next to each other is not a huge problem in my opinion because you had to do that before as well:

```js
const DragDrop = () => {
  const ref = useRef(null);

  const dragSource = {
    beginDrag() {
      return props;
    }
  };

  const collectSource = monitor => {
    return {
      isDragging: monitor.isDragging()
    };
  };

  const { isDragging } = useDragSource(ref, "Item", dragSource, collectSource);

  const dropTarget = {
    drop() {
      return undefined;
    }
  };

  const collectTarget = monitor => {
    return {
      isOver: monitor.isOver()
    };
  };

  const { isOver } = useDropTarget(ref, "Item", dropTarget, collectTarget);

  return <div ref={ref}>Drag me</div>;
};
```

The nice thing is that you can use values from other hooks as well.

```js
const Drag = () => {
  const ref = useRef(null);
  const context = useContext(Context)

  const dragSource = {
    beginDrag() {
      context.setDragItem(props)
      return props;
    },
    endDrag() {
      context.setDragItem(null)
    }
  };

  const collectSource = monitor => {
    return {
      isDragging: monitor.isDragging()
    };
  };

  const { isDragging } = useDragSource(ref, "Item", dragSource, collectSource);

  return <div ref={ref}>Drag me</div>;
};
```

**Comment by jacobp100** [comment] 2018-11-28 13:59
^ I just updated my last comment to show that `collectSource` doesn't pass in the monitor to the function - you just read from the scope

**Comment by k15a** [comment] 2018-11-28 14:19
@jacobp100	I see. For me, the question would be if we need another hook to collect data from the monitor or if we could implement it in the useDragSource and useDropTarget as well.

**Comment by jacobp100** [comment] 2018-11-28 14:29
It made sense when stuff was HOCs, where you had to link up the connect stuff anyway.

But there's now no technical requirement to couple them anymore, so I left them separate.

Then you have more freedom with them - maybe one or more child components to respond to monitor changes, but not the component that is begin dragged. It also has an added bonus that if you aren't using monitor subscriptions, that hook can be tree shaken.

That said, this is an initial draft! I'm not opposed to changing it if that's the consensus!

**Comment by k15a** [comment] 2018-11-28 14:50
That's a good argument. The one and only problem I see is that user could be confused when they call the monitor directly and wonder why it doesn't behave correctly:

```js
const Test = (props) => {
  const ref = useRef(null)

  const sourceMonitor = useDragSource(ref, 'item', {
    beginDrag: () => ({ id: props.id })
  })

  const targetMonitor = useDropTarget(ref, ['item'], {
    drop: () => alert(targetMonitor.getItem().id)
  })

  const { isDragging } = useMonitor(targetMonitor, () => ({
    isDragging: targetMonitor.isDragging()
  })

  return <div ref={ref}>{sourceMonitor.isDragging() ? 'Dragging' : 'Drag me'}</div>
}
```

Probably that can be solved with documentation and warnings when you call the function outside of the `useMonitor` hook.

**Comment by jacobp100** [comment] 2018-11-28 15:07
Actually, that will work! It's one of the things I'm not 100% keen on: the callback in `useMonitor` is used both for change detection and the return value. It feels like it's going against the current hooks in React core.

Maybe something like this works better,

```js
const Test = (props) => {
  ...
  useMonitorUpdates(targetMonitor, () => [targetMonitor.isDragging()]);

  return <div ref={ref}>{sourceMonitor.isDragging() ? 'Dragging' : 'Drag me'}</div>
}
```

**Comment by k15a** [comment] 2018-11-28 15:16
I am not 100% sure of the react-dnd internals but isn't the monitor there so we don't have to render the component everytime your mouse moves?

So the previous would stop working if you remove the useMonitorSubscription and only have `monitor.isDragging()` in the render function?


This would therefore not work correctly? 
```
const Test = (props) => {
  const ref = useRef(null)

  const sourceMonitor = useDragSource(ref, 'item', {
    beginDrag: () => ({ id: props.id })
  })

  return <div ref={ref}>{sourceMonitor.isDragging() ? 'Dragging' : 'Drag me'}</div>
}
```

**Comment by jamestalmage** [comment] 2019-01-07 03:12
A couple ideas.

First, can we make the `ref` argument optional? If it's not passed as the first argument have the hook return a `ref` implementation as `monitor`?

```js
const dragSource = useDragSource('item', spec);
return <div ref={dragSource}/>
```

Rather than making them invoke another hook in `useMonitorUpdates`, I wonder if we can just do the following: 

```js
const dragSource = useDragSource('item', spec);

const { isDragging } = dragSource.subscribe(() => ({
  isDragging: targetMonitor.isDragging()
}));
```

**Comment by darthtrevino** [comment] 2019-03-11 18:50
I'm going to close this for now, since there's a candidate API. Feel free to comment on that with new issues though. Thanks!

**Comment by k15a** [comment] 2019-03-19 13:58
Looks like the hooks API has a flaw in the design: https://github.com/Swizec/useDimensions/issues/3

**Comment by darthtrevino** [comment] 2019-03-19 17:27
How does this affect the react and hook design?

**Comment by darthtrevino** [comment] 2019-03-19 17:28
How does this affect the react dnd hook design?

**Comment by darthtrevino** [comment] 2019-03-19 17:45
Interesting, so I guess an alternative is that we use a connect function, like in the class-based API:

```js

const Box = ({ name }) => {
    const [{ isDragging }, dragSource] = useDrag({
        item: { name, type: ItemTypes.BOX },
        end: (dropResult?: { name: string }) => {
            if (dropResult) {
                alert(`You dropped ${item.name} into ${dropResult.name}!`)
            }
        },
        collect: monitor => ({
            isDragging: monitor.isDragging(),
        }),
    })
    const opacity = isDragging ? 0.4 : 1

    return (
        <div ref={node => dragSource(node)} style={{ ...style, opacity }}>
            {name}
        </div>
    )
}
```

**Comment by darthtrevino** [comment] 2019-03-19 17:51
As I read that issue though - our APIs are similar, but I think the problem there is that they're using a layout effect to get the measurement of a DOM node. We're not really using layout effects here, just registering DOM nodes with the dnd-core.

**Comment by darthtrevino** [comment] 2019-03-19 17:54
@gaearon , our proposed hooks API is very similar to the useDimensions API - is that specific form an antipattern (e.g. `let [props, ref] = useCustomHook(config)`), or is it idiosyncratic to the problem that library is trying to solve?

**Comment by k15a** [comment] 2019-03-19 22:39
@darthtrevino As far as I understand if you use the useDragSource hook and you pass the ref down to a child component and the child component rerenders we will not update the registered dom node in dnd-core:

```js
function Parent() {
  const ref = useRef();
  const dragSource = useDragSource(ref, ...);

  return <Child connect={ref} />;
}

function Child({ connect }) {
  const [open, setOpen] = useState(false);

  function toggle() {
    setOpen(!open);
  }

  return (
    <Fragment>
      <button onClick={toggle}>Toggle</button>
      {open ? <div ref={connect} /> : null}
    </Fragment>
  );
}
```

**Comment by darthtrevino** [comment] 2019-03-19 22:46
Yech. I'll see if I can make a test case for this later this week to prove whether it blows up or not

**Comment by darthtrevino** [comment] 2019-03-19 22:47
If it blows up, using connector functions will be the fallback

**Comment by k15a** [comment] 2019-03-19 23:13
If I did everything correctly I was able to reproduce it here: https://codesandbox.io/s/xj7k9x4vp4

**Comment by darthtrevino** [comment] 2019-03-19 23:17
Kaboom, good work, thanks @k15a . I'll update the hooks API to use connect functions soon and include your example as a test case

**Comment by darthtrevino** [comment] 2019-03-20 16:51
So I spent a bunch of time last night reworking the hooks API to use connector functions. As far as API design goes, I really fucking hate it. 

My next thought is that we can return a callback-ref instead of a ref-object. This should give us flexibility to use as a ref directly or to pass a ref into it

Using Directly:
```js
let [props, dragSource] = useDrag({spec}) // dragSource result is a function
return <div ref={dragSource} {...props}>hey</div>
```

Chaining
```js
let [dragProps, dragSource] = useDrag({spec})
let [dropProps, dropTarget] = useDrag({spec})

return <div ref={node => dragSource(dropTarget(node))}>hey</div>
```

With Ref Object
```js
let ref = useRef(null)
let [dragProps, dragSource] = useDrag({spec})
let [dropProps, dropTarget] = useDrag({spec})
dragSource(dropTarget(ref))

return <div ref={ref}>hey</div>
```

**Comment by jacobp100** [comment] 2019-03-20 17:43
To me, it feels like `useLayoutEffect` should fire if the component or any of its children updates. If it did, we could just use that.

[I've created a ticket in the react repo](https://github.com/facebook/react/issues/15167). Feel free to comment.

**Comment by k15a** [comment] 2019-03-20 18:01
```js
let [dragProps, dragSource] = useDrag({spec})
let [dropProps, dropTarget] = useDrag({spec})

return <div ref={node => dragSource(dropTarget(node))}>hey</div>
```

I don't know how good this works as you would call the ref with every single render. So with every render, you would need to connect and disconnect.

Also wouldn't it be better to have so 

```js
node => {
	dragSource(node)
	dropTarget(node)
}
```

**Comment by darthtrevino** [comment] 2019-03-20 19:34
It's would be the same thing

**Comment by darthtrevino** [comment] 2019-03-20 19:35
So, to ease up on my earlier comment, the API in #1280 is shaping up to be better than I first thought. Feel free to comment here or there

**Closed** 2019-06-07 20:54 UTC
Labels: design decisions, discussion
