### ISSUE TITLE
Monitor.getSourceClientOffset() returns inaccurate position when using Custom Drag Layer

### ISSUE THREAD

**Issue by Nathaniel-Fernandes** [react-dnd/react-dnd#2638] opened 2020-06-29 03:49 UTC
### SEE WORKAROUND AT BOTTOM ###
**Describe the bug**
I am building a chessboard. I created a custom drag layer with movable pieces on it. Whenever I click an element and BARELY drag it (I mean a microscopic amount), the image momentarily jumps about 137px up and 67px to the left before returning to the correct position. This only happens when I initially pick up the piece and doesn't happen again until I release it and pick it up again. I wondered if it was just me, but I managed to reproduce this bug on the [official React-DND custom drag layer example](https://codesandbox.io/s/github/react-dnd/react-dnd/tree/gh-pages/examples_hooks_js/02-drag-around/custom-drag-layer?from-embed=&file=/src/CustomDragLayer.jsx) - see video #2. 

I captured this behavior on slo-mo video. It happens at 0:02 and 0:23/24 in the chess video and 0:05 and 0:30 seconds in the other video.

[Video 1 - Chess](https://www.dropbox.com/s/1cypnkgdu54at0s/IMG_2360.MOV?dl=0)
[Video 2 - Other](https://www.dropbox.com/s/1d9kgxp2mv5o0u9/IMG_2357.MOV?dl=0)

This has to be the Monitor.getSourceClientOffset() values because I console logged it and it shows this jump. See image.
![IMG-2362](https://user-images.githubusercontent.com/66634653/85970834-35122700-b991-11ea-93ea-985e2d2de4e9.jpg) 

**Reproduction**

1. Go to [official React-DND custom drag layer example](https://codesandbox.io/s/github/react-dnd/react-dnd/tree/gh-pages/examples_hooks_js/02-drag-around/custom-drag-layer?from-embed=&file=/src/CustomDragLayer.jsx)
2. Click on the box.
3. Barely move your cursor
4. See the box jump momentarily.

**Expected behavior**
I would expect the chess piece to always remain under the cursor. If it jumps around even for a microsecond, it's incredibly distracting and looks unprofessional.

**Screenshots**
If applicable, add screenshots to help explain your problem

**Comment by Merlin-the-Warlock** [comment] 2020-06-29 03:55
I forgot to add my code. This is in my CustomDragLayer.js file. Thanks in advance for your speed response!

```import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { DragLayer } from 'react-dnd';

import { renderChessPiece } from './Piece';

const layerStyles = {
  position: 'fixed',
  pointerEvents: 'none',
  zIndex: 10,
  left: 0,
  top: 0
};

const getItemStyle = (currentOffset, wasPieceTouched) => {
  if (!currentOffset) return { display: 'none' };

  let { x, y } = currentOffset;
  const transform = wasPieceTouched
    ? (`translate(${x}, ${y + -25}px) scale(2)`)
    : `translate(${x}px, ${y}px)`;

  // console.log(transform);
  return { transform };
};

class CustomDragLayer extends Component {
  static propTypes = {
    item: PropTypes.object,
    currentOffset: PropTypes.shape({
      x: PropTypes.number.isRequired,
      y: PropTypes.number.isRequired
    }),
    isDragging: PropTypes.bool.isRequired,
    width: PropTypes.number,
    pieces: PropTypes.object,
    id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
    wasPieceTouched: PropTypes.bool,
    sourceSquare: PropTypes.string
  };
  
  render() {
    const {
      isDragging,
      width,
      item,
      id,
      currentOffset,
      wasPieceTouched,
      pieces,
      sourceSquare
    } = this.props;

    // console.log(this.props);
    
    return isDragging && item.board === id ? (
      <div style={layerStyles}>
        <div style={getItemStyle(currentOffset, wasPieceTouched)}>
          {renderChessPiece({
            width,
            pieces,
            piece: item.piece,
            isDragging,
            customDragLayerStyles: { opacity: 1 },
            sourceSquare
          })}
        </div>
      </div>
    ) : null;
  }
}

function collect(monitor) {
  console.log(monitor.getSourceClientOffset());
  return {
    item: monitor.getItem(),
    currentOffset: monitor.getSourceClientOffset(),
    isDragging: monitor.isDragging()
  };
}

export default DragLayer(collect)(CustomDragLayer);```

**Comment by Merlin-the-Warlock** [comment] 2020-06-29 21:06
I discovered 2 interesting patterns! The problem isn't with the CustomDrayLayer - it turns out the issue is with the ClientOffset coordinates (which would affect the calculations with SourceClientOffset).

1. When I console logged the ClientOffset and SourceClientOffset, the "jump" always happens for 2 console logs on the 8th ClientOffset console log (ie. the 6th ClientOffset log after the first SourceClientOffset log).

That was really confusing, so here are pictures:
![IMG-2366](https://user-images.githubusercontent.com/66634653/86049247-6f260c00-ba17-11ea-8b2b-9e0bd1710a2e.jpg)
![IMG-2367](https://user-images.githubusercontent.com/66634653/86049254-71886600-ba17-11ea-8eba-b097d9d37af3.jpg)
![IMG-2368](https://user-images.githubusercontent.com/66634653/86049255-73522980-ba17-11ea-8d07-8293ee8ec3c8.jpg)

2. When you look at the difference in the x- and y-values of the jump, both the x- and y-values of the correct ClientOffset are always reduced by 33.33% (i.e. 1/3). I don't think that's a coincidence.
I have plotted the correct vs. jump values in these desmos graphs - X-values: https://www.desmos.com/calculator/m0vs2vcymd
Y-values: https://www.desmos.com/calculator/pfk04rj9fu

Because the error happens after the drag begins but before item is dropped, my best guess is that there is a bug in updating ClientOffset when the item **hovers**, either in 
 - "packages/core/dnd-core/src/reducers/dragOffset.ts" lines 39-46
 - creating the hover payload in "packages/core/dnd-core/src/interfaces.ts" lines 152-159
 - in the hover file "packages/core/dnd-core/src/actions/dragDrop/hover.ts"
 - or in "packages/core/dnd-core/src/interfaces.ts"

I honestly really don't know tho and am just waiting for a fix!!

**Comment by Merlin-the-Warlock** [comment] 2020-07-01 00:35
More discoveries: I realized the problem is actually most likely with the **html5-backend** and how it calculates the monitor offset. So the problem is probably in: packages/core/html5-backend/src/MonotonicInterpolant.ts or packages/core/html5-backend/src/OffsetUtils.ts

Also, the bug only shows up in Chrome and Opera. It is NOT present in Microsoft EDGE or Firefox if that helps.

**Comment by kosgo** [comment] 2020-07-01 19:21
+1 
bug is reproducible even at the demo page
https://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer

**Comment by Merlin-the-Warlock** [comment] 2020-07-19 19:50
WORKAROUND:

I still don't know why the HTML5 BackEnd has this error in the client offset calculation. But I found a workaround. 

Simply use the Touchbackend and set {enableMouseEvents: true}. Note - as per the official react-dnd website, there might be some bugs "due to the difference in touchstart/touchend event propagation compared to mousedown/mouseup/click."

However, I have not noticed any. Overall, the performance of drags has been a lot smoother and more professional.

PLUS, now I can customize the cursor when dragging and not have the annoying drag effect!!!

**Comment by ecfy** [comment] 2020-10-02 18:21
+1 on this issue -- Got exactly the same behavior as described by OP but unfortunately switching to the touch-backend is not an option for us since the different events being used also triggers undesired behavior in our app. Would love to see a fix for this.

**Comment by Ankit-Gupta-1511** [comment] 2020-11-11 04:45
+1 on this issue. I am also getting inaccurate coordinates with monitor.getSourceClientOffset(). The touch backend is not working as smoothly as HTML5Backend. This is extremely crucial for a project so, we are eagerly waiting for this fix. Thanks in advance.

**Closed** 2020-11-13 18:22 UTC
