### ISSUE TITLE
React 16: Stateless function components cannot be given refs

### ISSUE THREAD

**Issue by blord-fullscreen** [react-dnd/react-dnd#904] opened 2017-10-10 21:25 UTC
I'm using the latest dnd v2.5.4 and still getting a console error for calls to `DragLayer`, which is set up in my app as a stateless function component. This is very similar to #896, which concerned `DragDropContext`

Log:

```
warning.js:33 Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `DragLayer(SitePageCustomDragLayer)`.
    in SitePageCustomDragLayer (created by DragLayer(SitePageCustomDragLayer))
    in DragLayer(SitePageCustomDragLayer) (created by SitePageContainer)
    in div (created by PanelBody)
    in PanelBody (created by SitePageContainer)
```

**Comment by tough-griff** [comment] 2017-10-13 16:39
I too am still seeing the `Stateless function components cannot be given refs.` warning when using the following helper in my tests:

```jsx
const wrapInTestContext = (WrappedComponent) => {
  const TestContextWrapper = props => (
    <Provider store={store}>
      <StaticRouter context={context}>
        <WrappedComponent {...props} />
      </StaticRouter>
    </Provider>
  );

  return DragDropContext(TestBackend)(TestContextWrapper);
};
```

Defining `TestContextWrapper` as a class removes the warning.

**Comment by bkniffler** [comment] 2017-10-15 01:06
https://github.com/acdlite/recompose/blob/master/docs/API.md#toclass works great as workaround.

**Comment by larube** [comment] 2017-10-16 11:57
@bkniffler could you please give an example ?

**Comment by DanielRuf** [comment] 2017-12-05 11:59
You may have to rewrite it to a class.

**Comment by DanielRuf** [comment] 2017-12-05 12:05
https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc

**Comment by neekey** [comment] 2017-12-06 05:05
I have the same warning with `DragDropContext()`

```
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `DragDropContext(WorkspaceList)`.
    in WorkspaceList (created by DragDropContext(WorkspaceList))
    in DragDropContext(WorkspaceList) (created by provideMountCallbacks(DragDropContext(WorkspaceList)))
    in provideMountCallbacks(DragDropContext(WorkspaceList)) (created by Connect(provideMountCallbacks(DragDropContext(WorkspaceList))))
    in Connect(provideMountCallbacks(DragDropContext(WorkspaceList))) (created by IndexContainer)
    in IndexContainer (created by Connect(IndexContainer))
    in Connect(IndexContainer) (created by RouterContext)
    in div (created by App)
    in LoadingContent (created by App)
    in div (created by App)
    in LocaleProvider (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Connect(Connect(App)))
    in Connect(Connect(App)) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider
```

Guess I have to change `WorkspaceList` to class...

**Comment by neekey** [comment] 2017-12-06 05:33
@DanielRuf sure, and need to mention that if you don't need to setup state or bind callbacks you don't have to include `constructor`

**Comment by DanielRuf** [comment] 2017-12-06 05:48
I know but I've added it to prepare next versions which will use some config props.

It's also just there for reference, it does not hurt.

**Comment by guynimni382** [comment] 2017-12-20 13:46
I'm having this issue when using redux, which wraps another wrapper:
DragDropContext(HTML5Backend)(connect(mapStateToProps, mapDispatchToProps, null, { withRef: true })(withRouter(FiltersSideBar)));

No matter who wraps who I get this error.
Any ideas?

**Comment by Cristy94** [comment] 2017-12-22 10:24
I still get this error, how to fix it without changing the entire codebase and replacing stateless components with classes?

**Comment by bkniffler** [comment] 2017-12-22 10:39
Still, I hope sometime there will be a fix for this issue, but for now using recompose toClass seems like the easiest way (and easiest to get rid of as soon as the issue is resolved). Borrowing @tough-griff example:
```
import { toClass } from 'recompose';

const wrapInTestContext = (WrappedComponent) => {
  const TestContextWrapper = toClass(props => (
    <Provider store={store}>
      <StaticRouter context={context}>
        <WrappedComponent {...props} />
      </StaticRouter>
    </Provider>
  ));

  return DragDropContext(TestBackend)(TestContextWrapper);
};
```

**Comment by DanielRuf** [comment] 2017-12-22 11:34
This is intended. You should change it to a class.

**Comment by MadeoIT** [comment] 2018-07-04 11:37
You can wrap your functional component with a div and give a ref to that div

**Comment by wilk** [comment] 2018-11-26 10:23
What about wrapping it in a `React.Fragment` component?
It should work.

**Comment by nathanredblur** [comment] 2019-01-23 16:15
Then... not exist other solution?
Convert the component to a class or wrap it on a div?

**Comment by DanielRuf** [comment] 2019-01-23 16:20
> Convert the component to a class

Either this as the error says or use one of the new solutions (fragments).

**Comment by DanielRuf** [comment] 2019-01-23 16:21
> Defining TestContextWrapper as a class removes the warning.

Still the best solution imo.

**Comment by yched** [comment] 2019-03-26 11:22
#1280 in the recent 7.4.0 made the issue appear for us with DragDropContext

We had DragDropContext decorating a function component, it worked fine so far, and now spits a "Function components cannot be given refs" error.

**Comment by darthtrevino** [comment] 2019-03-26 22:33
The warnings have been removed in a patch version. You can use React.forwardRef to get actual ref instances.

**Closed by darthtrevino** 2019-03-26 22:33 UTC
