### ISSUE TITLE
React DnD not work on Chrome 59 

### ISSUE THREAD

**Issue by hunterbmt** [react-dnd/react-dnd#789] opened 2017-06-08 09:42 UTC
After upgrading to Chrome 59,  react-dnd no longer works. After a bit investigating, it looks like Chrome no longer triggers "dragend" event which leads to react-dnd misunderstand when I try to drag the second item/time
Anyone experience the same issue?

**Comment by theTechie** [comment] 2017-06-09 06:54
Not the case; it work's perfectly fine. Try running Chrome without any extensions

**Comment by hunterbmt** [comment] 2017-06-09 07:50
@theTechie did you check on Mac on Windows ? On Mac it's working normally.

**Comment by theTechie** [comment] 2017-06-09 10:36
i checked on Mac. Is it a problem with a specific platform?

**Comment by hunterbmt** [comment] 2017-06-12 02:22
@theTechie for some reason, react-dnd don't trigger 'dragend' as normal. I tested on couple machine, one Mac has the same issue, all Windows has this issue. Any thought?

**Comment by theTechie** [comment] 2017-06-13 02:57
I tested on multiple platforms Windows 8.1 / Windows 7 on Chrome and also on IE 10 and IE 11. It works fine for me. 

@hunterbmt - Do you see any errors in the console ? could you share a GIF for some context?

**Comment by hunterbmt** [comment] 2017-06-14 10:01
@theTechie I tested on example site of react dnd, didn't have any issue. But in our application, Chrome 59 didn't trigger 'dragend' in some scenarios which works perfectly normal on Chrome 58, FF, Safari and even IE.
I fixed by manually trigger 'dragend' after 'drop' if the browser didn't trigger it after a while. 
I don't know if others fail into this issue as well, if that's the case, I could move the fix into react-dnd.

Looking at the changelog of Chrome 59 but didn't find anything, if you have any insight, I will appreciate the input a lot.

**Comment by theTechie** [comment] 2017-06-15 06:46
I think it could be something peculiar to your code; even i have used react-dnd in multiple instances and all of them work fine on Chrome 59.

Unfortunately, i am unable to tell you why this would be happening. Maybe, i can try and find something if you are ok sharing your code here.

**Comment by awestroke** [comment] 2017-06-15 14:54
I have the same problem in Chrome 59.0.3071.86 on Windows. It works fine in Firefox, and worker fine in earlier Chrome versions. package.json:
```json
{
  "dependencies": {
    "react-dnd": "2.1.4",
    "react-dnd-html5-backend": "2.1.2",
  }
}
```

**Comment by awestroke** [comment] 2017-06-15 15:35
Solved with this hack:

```js
const ModifiedBackend = (...args) => {
	const instance = new HTML5Backend(...args);

	// Fix Chrome 59 not sending a DragEnd after Drop, which other browsers do and react-dnd expects
	const originalTopDrop = instance.handleTopDrop;
	const originalTopDragEndCapture = instance.handleTopDragEndCapture;
	let dragEndTimeout;
	instance.handleTopDrop = (e, ...args) => {
		dragEndTimeout = setTimeout(() => {
			originalTopDragEndCapture(e, ...args);
		}, 0);
		originalTopDrop(e, ...args);
	};
	instance.handleTopDragEndCapture = (e, ...args) => {
		clearTimeout(dragEndTimeout);
		originalTopDragEndCapture(e, ...args);
	};

	return instance;
};

// Decorate root elements with this
export default DragDropContext(ModifiedBackend);
```

**Comment by hunterbmt** [comment] 2017-06-15 15:42
@awestroke I end up with quite similar hack but the issue still happen when I quick drag and drop in undroppable area, Chrome fail to trigger 'dragend' and of course, won't trigger 'drop' as well. Could you check from your side ?

**Comment by awestroke** [comment] 2017-06-16 05:58
@hunterbmt I have no problems with dropping in undroppable areas. I haven't checked which events are triggered, but react-dnd doesn't enter a corrupted state, so everything seems to work well.

**Comment by hunterbmt** [comment] 2017-06-19 09:33
I created a PR to fix this issue and potential issues by simplifying the condition to trigger endDrag
https://github.com/react-dnd/react-dnd/pull/801

**Comment by rogyvoje** [comment] 2017-07-16 22:09
I have the same problem although not every time, just in some cases, and for example that case is:
I have a widget that can be dropped inside drop area, and that drop area will render some html when widget is dropped. If I choose to drop video widget it will render `iframe` and it breaks and I can't drag any other widgets after that (`dragend` event is not fired). But if I replace that `iframe` with some text or image, it works perfectly fine, and it was working before Chrome 59, and it works in any other browser, I can't figure it out, is the problem in Chrome or react-dnd?

**Comment by hunterbmt** [comment] 2017-07-17 08:37
@rogyvoje I believe that Chrome changed something in event triggering for 'dragend'. Tried to search for more information but I don't see them mention that anywhere.
Btw, depending on 'mousemove' after 'dragstart' make more sense and simpler that depending on 'dragend' in most of the case and 'mousemove' in some cases (dragging element removed from DOM) as my PR.

**Comment by rogyvoje** [comment] 2017-07-17 08:59
@hunterbmt thanks for demystifying 😄 
but how can I use your pull request through npm/yarn? Because it seems that it is not merged, or am I wrong? 😕

**Comment by hunterbmt** [comment] 2017-07-17 09:27
@rogyvoje I think you can, instead of the version just point to my branch directly. PR was merged but react-dnd is not yet released new version so you cannot get it directly from react-dnd npm/yarn.

**Comment by rogyvoje** [comment] 2017-07-24 14:59
@hunterbmt 
I tried to do it like this:

`npm install git+https://github.com/react-dnd/react-dnd.git#41eb8caa0bc106c9edf0d3ca628b49e70525090b`

but login screen always pop up 😕

**Comment by bjrmatos** [comment] 2017-07-25 15:44
can anyone in this thread provide a reproducible case of the problem? i'm using `react-dnd` a lot but i can not identify any issue on Chrome 59, so i'm very interested to have a reproducible case where `react-dnd` fails because Chrome 59 does not fire `drag/drop` events correctly.

i think if there is a problem, it should be reproducible very easily by some of you that saw the problem in the first place, so please try to take the time to post a reproducible case (it can be a github repo or code posted here https://codesandbox.io/) and try to provide any meaningful information (like OS, version of react-dnd, etc). thnks!

**Comment by rogyvoje** [comment] 2017-07-25 19:35
@bjrmatos here, I made one, this one is my case and I hope it will help!

https://github.com/rogyvoje/react-dnd-chrome-59

**Comment by bjrmatos** [comment] 2017-07-25 20:02
@rogyvoje thnks! i will take a look later, let's see if i can see the problem in my windows 7 VM, otherwise i will try another VM with windows 10. thnks!

**Comment by bjrmatos** [comment] 2017-07-28 17:30
hi @rogyvoje i've tried your repository directly in the latest chrome release as you said that you had the same problem there (Version 60.0.3112.78 (Official Build) (64-bit)) but i don't see any error.

this is the expected result, right?

![captura de pantalla 2017-07-28 a las 12 29 32 p m](https://user-images.githubusercontent.com/4262050/28729007-7b4f8586-7390-11e7-9f43-e8420a96f211.png)


are there any other steps to reproduce your issue?

i've installed the dependencies with `npm@5.3.0` (instead of using `yarn`) and just for the record here are the exact versions of dependencies installed:

![captura de pantalla 2017-07-28 a las 12 25 43 p m](https://user-images.githubusercontent.com/4262050/28728875-ec2051c4-738f-11e7-9d6e-29c1bebef52f.png)


NOTE: i'm using a windows 10 PRO VM (because my main OS is OSX El Capitan, in which the issue with chrome does not exists)
![captura de pantalla 2017-07-28 a las 12 22 23 p m](https://user-images.githubusercontent.com/4262050/28728755-6e7c6adc-738f-11e7-8372-396d07311cf0.png)

**Comment by bjrmatos** [comment] 2017-07-28 17:35
and same result with all my chrome extensions disabled:

![captura de pantalla 2017-07-28 a las 12 34 31 p m](https://user-images.githubusercontent.com/4262050/28729180-29d35d76-7391-11e7-9c5e-5158ac76c569.png)

**Comment by bjrmatos** [comment] 2017-07-28 18:03
@rogyvoje  i've just read your past comments and now i can reproduce the problem, as you say the first drag works, but if someone try dragging a second time the `Cannot call hover after drop` error appears.

thnks for the repository, i will try to dive into the problem and look for a solution that makes everybody happy.

**Comment by bjrmatos** [comment] 2017-07-28 18:08
seems like the bug is confirmed: https://bugs.chromium.org/p/chromium/issues/detail?id=737691&q=dragend&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

https://stackoverflow.com/questions/44764343/dragend-event-not-firing-in-chrome-when-an-iframe-is-moved-in-drop-function

**Comment by bjrmatos** [comment] 2017-07-28 18:32
for the record i can reproduce the error with the same [example](rogyvoje/react-dnd-chrome-59) also in Chrome (60) Mac OS (El Capitan) (not sure about if it was present also in Chrome 59 for Mac), so it is failing everywhere when using Chrome and when using iframes 😂

**Comment by rogyvoje** [comment] 2017-07-28 18:38
@bjrmatos great, glad that you successfully reproduce it 😄 
just not sure what's going to happen next, should we wait for Chrome 61? 😂

**Comment by bjrmatos** [comment] 2017-07-28 18:46
> just not sure what's going to happen next, should we wait for Chrome 61?

maybe, anyway i'm trying to find a nice patch that makes react-dnd work in Chrome 59, 60, so i will post here more updates later 👍

**Comment by ms88privat** [comment] 2017-08-31 16:48
I think this solves the problem. https://github.com/react-dnd/react-dnd/pull/820
It is already merged, but not released.

**Comment by NiceGuyNimni** [comment] 2018-02-25 09:01
Any news regarding this issue?
I'm still having issues in the latest chrome...

**Comment by miadabrin** [comment] 2018-10-02 11:31
it also freezes when you include in iframe in the page inside chrome (59 till current) @0rvar 's fix works in this case as well

**Comment by davidspiess** [comment] 2019-01-30 08:58
This is fixed now in chrome 72, which was released yesterday.

**Closed** 2019-07-13 02:48 UTC
Labels: wontfix
