### ISSUE TITLE
How to get newest props in hook api?

### ISSUE THREAD

**Issue by a358385960** [react-dnd/react-dnd#1354] opened 2019-05-23 02:08 UTC
Hi here. I'd like to access component props info from dnd useDrop hooks, `hover()` function, however i can only get the initial props value. What's wrong?

Here is an example, whatever now count change, `nowCount` in `hover()` printed is always 0.
https://codesandbox.io/s/reactdndexample3-xvjvy?fontsize=14

**Comment by srph** [comment] 2019-05-25 23:37
Having the same issue here. Will investigate what seems to be the issue.

By the way, your CodeSandbox link seems to be oudated. I can't see the `hover` callback you mentioned.

**Comment by srph** [comment] 2019-05-25 23:45
Edit: I think this issue is a duplicate of https://github.com/react-dnd/react-dnd/issues/1326

**Comment by darthtrevino** [comment] 2019-06-07 07:12
Please try out 7.5.0

**Closed** 2019-06-07 17:15 UTC
