### ISSUE TITLE
Hooks API uses outdated version of spec with old closures

### ISSUE THREAD

**Issue by gavinwahl** [react-dnd/react-dnd#1326] opened 2019-04-16 16:29 UTC
1. Go to https://codesandbox.io/s/2po0o7pmo0
2. Drag the drag label into the box. See the count updated to 1
3. Drag the label into the box again. The count should go to 2 but it stays at 1

The useDrop is hanging on to an old version of the drop() callback which closes over an old version of the state. It needs to use the version passed to it most recently.

cc @darthtrevino @yched

**Comment by jakyle** [comment] 2019-04-21 20:02
ran into a similar problem when going over the codebase for [drag around naive](http://react-dnd.github.io/react-dnd/examples/drag-around/naive?experimental) experimental example.  essentially any time you hit the drop function in a drop component 

```ts
const [, drop] = useDrop({
		accept: ItemTypes.BOX,
		drop(item: DragItem, monitor) {
			const delta = monitor.getDifferenceFromInitialOffset() as XYCoord
			const left = Math.round(item.left + delta.x)
			const top = Math.round(item.top + delta.y)
			moveBox(item.id, left, top)
		},
	})
```
same issue as @gavinwahl , you will get an old version of useDrop(), it never updates more than once.

**Comment by chrisjallen** [comment] 2019-04-23 21:34
Found same issue, the drop callback seems to be memoized and all references are from the previous stack/closure. To circumvent this problem (until a fix is raised), use a ref hook to store your required/updated value.

@gavinwahl, here is a snippet to fix your problem...

```
let App = () => {
  const [dropCount, setDropCount] = useState(0);
  const hackDropCountRef = useRef();
  hackDropCountRef.current = dropCount;
  const [{}, drag] = useDrag({
    item: {
      type: "foo"
    }
  });
  const [{ isOver }, drop] = useDrop({
    accept: "foo",
    drop() {
      // despite this being a stored function and old closure, the object reference will still remain the same
      const dropCount = hackDropCountRef.current;
      // now incrementing :)
      setDropCount(dropCount + 1);
      console.log("dropped ");  
    },
    collect(monitor) {
      return {
        isOver: monitor.isOver()
      };
    }
  });

```

working on example: 
[https://codesandbox.io/s/yp39417p91](url)

**Comment by jamiewinder** [comment] 2019-05-02 09:16
Hopefully this is helpful. I ran the project through eslint using the `eslint-plugin-react-hooks` plugin and this identified the following uses of `useMemo` which may be causing this:

#### react-dnd\src\hooks\internal\drag.ts
```
  75:5   warning  React Hook useMemo has missing dependencies: 'connector', 'monitor', and 'spec'. Either include them or remove the dependency array
  react-hooks/exhaustive-deps
  87:5   warning  React Hook useEffect has missing dependencies: 'connector', 'handler', 'manager', 'monitor', and 'spec'. Either include them or remove the dependency array
  react-hooks/exhaustive-deps

```

#### react-dnd\src\hooks\internal\drop.ts
```
  56:5   warning  React Hook useMemo has a missing dependency: 'spec'. Either include it or remove the dependency array                                react-hooks/exhaustive-deps
  70:3   warning  React Hook useEffect has missing dependencies: 'handler', 'manager', and 'spec'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
```

#### react-dnd\src\hooks\internal\useMonitorOutput.ts
```
  23:3  warning  React Hook useEffect has a missing dependency: 'updateCollected'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
```

#### react-dnd\src\hooks\useDrop.ts
```
  42:5   warning  React Hook useEffect has a missing dependency: 'connector'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
```

**Comment by jamiewinder** [comment] 2019-05-02 09:55
Actually, the cause seems to be more simple than that. The initial `spec` is used as the initial value to a ref:
```ts
const specRef = useRef(spec);
```
And thereafter, the spec is only read from this ref so of course it'll always be the initial value. 

[useDrag](https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/hooks/useDrag.ts#L24)
[useDrop](https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/hooks/useDrop.ts#L23)

Adding a simple `specRef.current = spec` after these lines appears to solve the problem for me, though of course this renders the whole use of a ref unnecessary in the first place.

**Comment by JKillian** [comment] 2019-05-02 15:29
Hit this myself, agreed that the current behavior isn't intuitive given the overall paradigm of React hooks. @darthtrevino would you accept a PR to fix this? (Or want to fix it yourself if that's easier?) Love using the hook API overall, it's much nicer than HoCs or decorators in my opinion!

**Comment by darthtrevino** [comment] 2019-05-02 15:39
I'd be glad to look at a pr, for sure. This is a community project

**Comment by JKillian** [comment] 2019-05-03 19:31
Found an example of an issue this is causing in the [official 'Drag sourcesl example](http://react-dnd.github.io/react-dnd/examples/nesting/drag-sources?experimental). Note how disabling drag does not work:

![2019-05-03 15 30 13](https://user-images.githubusercontent.com/1400151/57161036-89833c00-6db8-11e9-84c8-bf09880697e2.gif)

**Comment by JKillian** [comment] 2019-05-03 20:40
I didn't end up having enough time today to look at a fix in-depth, but I do agree that `spec` likely doesn't need to be a ref and should instead just be passed in as an object. Users of the API can memoize their spec like below if they're worried about recreating objects:

```
const dropSpec = useMemo(() => ({
  accepts: someConstant,
  drop: (item) => setSomeState(item + someProp),
}), [someProp]);
const [_, dropRef] = useDrop(dropSpec); 
```

Or they can memoize individual functions, like their `drop` function if they desire. The hook implementations themselves should be able to trust the user to provide referentially equal values when necessary.

Not sure though if this will cause any tricky implementation issues or not, but it seems like the most idiomatic way to implement things!

**Comment by LukePetruzzi** [comment] 2019-05-20 17:00
@JKillian, any update on your ideas for a new implementation? We're building a ui that allows for drag and drop anywhere within a window (so similar to the 'drag around naive' example), and would love to test with hooks when these are a bit more stable.

**Comment by JKillian** [comment] 2019-05-21 02:32
@LukePetruzzi, unfortunately, I haven't had a chance to spend the time to fix this. I gave it a brief go at one point, but hit some issue with something related to 'subscriptions' I believe and didn't have a chance to familiarize myself with the library enough to figure out what was happening.

Definitely a worthwhile issue for someone to look in to if they have enough time though! The hooks API seems very nice, and getting the implementation polished is a quality contribution.

**Comment by darthtrevino** [comment] 2019-06-07 07:11
This should be fixed in 7.5.0 - we set Ref.current when the hook fires. Thanks for pointing that out @jamiewinder.

**Closed by darthtrevino** 2019-06-07 07:11 UTC

**Comment by darthtrevino** [comment] 2019-06-07 16:25
I think we're getting close to the hooks API being stable. The perf in the Sortable stress test is the last thing I want to nail down

**Comment by darthtrevino** [comment] 2019-06-07 17:16
And that's done now.

I guess it's time to ship the hooks api 🤷‍♂️

**Comment by JKillian** [comment] 2019-06-07 21:16
Amazing, thanks! Trying out 7.6.0 right now and looks like all the previous issues are gone and the hooks API is working well! 💯
